export const INITIALIZE = "INITIALIZE";
export const SAVE_TRIP = "SAVE_TRIP";
export const EDIT_TRIP = "EDIT_TRIP";
export const DELETE_TRIP = "DELETE_TRIP";
export const DAILY_TRIPS_GOAL_CHANGE = "DAILY_TRIPS_GOAL_CHANGE";
export const DAILY_ACTIVE_TRIPS_GOAL_CHANGE = "DAILY_ACTIVE_TRIPS_GOAL_CHANGE";
export const DAILY_CARPOOLING_TRIPS_GOAL_CHANGE =
  "DAILY_CARPOOLING_TRIPS_GOAL_CHANGE";
export const CHANGE_USER_NAME = "CHANGE_USER_NAME";
export const CHANGE_USER_ADDRESS = "CHANGE_USER_ADDRESS";
